import LayoutAdmin from '@/layout/admin/LayoutAdmin';
import '../../assets/styles/globals.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Admin Shop',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<LayoutAdmin>{children}</LayoutAdmin>
			</body>
		</html>
	);
}
